title: Evaldas Jablonskas
description: Microsoft Dynamics 365 Business Central / NAV Developer

url: "https://evaldasjablonskas.lt"
baseurl: ""

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
